# Generated by Django 4.2.11 on 2024-03-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Detail',
            new_name='detail',
        ),
    ]
