# Generated by Django 4.2.11 on 2024-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_detail_patient_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_visit',
            field=models.CharField(default=0),
        ),
    ]
