# Generated by Django 4.2.11 on 2024-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_next_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_visit',
            field=models.IntegerField(default=0),
        ),
    ]
