# Generated by Django 4.2.11 on 2024-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_next_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
