# Generated by Django 4.2.11 on 2024-03-25 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_added_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
